create blank of Loan Calc application
PkozlovTCS/qa-automation-java pull request #2
Opened 2021-08-13 23:53 UTC by PkozlovTCS

2021-08-14 10:53 UTC, kkmikhaylova requested changes
Привет!
По логике всё сделано верно, круто 👍 
Отписала несколько комментов по код стайлу и архитектуре, но ничего криминального не вижу. Тут скорее к лекции и заданию вопросы

2021-08-14 10:53 UTC, kkmikhaylova commented on app/src/main/java/com/tinkoff/edu/app/LoanCalcController.java
> +
Лишняя пустая строка

2021-08-14 10:53 UTC, kkmikhaylova commented on app/src/main/java/com/tinkoff/edu/app/LoanCalcController.java
> +        LoanCalcLogger.log();
Метод log ничего не логирует, должен быть залогирован requestId, как я понимаю

2021-08-14 10:53 UTC, kkmikhaylova commented on app/src/main/java/com/tinkoff/edu/app/LoanCalcLogger.java
> +    public static void log() {
Пустой метод, в проекте никогда такого быть не должно

2021-08-14 10:53 UTC, kkmikhaylova commented on app/src/main/java/com/tinkoff/edu/app/LoanCalcRepository.java
> +        int localVar = ++requestId;
Зачем здесь переменная localVar? Можно справиться и без неё

2021-08-14 10:53 UTC, kkmikhaylova commented on app/src/main/java/com/tinkoff/edu/app/LoanCalcService.java
> +        int localVar;
Неиспользуемая переменная localVar

2021-08-14 10:53 UTC, kkmikhaylova commented on app/src/main/java/com/tinkoff/edu/app/LoanCalcRepository.java
> +
Коммент от метода не отделяется пустой строкой

2021-08-14 10:53 UTC, kkmikhaylova commented on app/src/main/java/com/tinkoff/edu/test/LoanCalcTest.java
> +
Коммент от метода не отделяется пустой строкой

2021-08-14 10:53 UTC, kkmikhaylova commented on app/src/main/java/com/tinkoff/edu/test/LoanCalcTest.java
> +        System.out.println(requestId + "must be 1");
А в чём смысл этого теста? Он же ничего не тестирует, просто в консоль выводит результат
Если результат будет не 1, то этот тест никак не повлияет на сборку проекта
Вы же подключали junit, почему он не использован?
Или "Self-made tests implemented (with main class)" это вот это и значило?)

2021-08-14 10:53 UTC, kkmikhaylova commented on app/src/main/java/com/tinkoff/edu/app/LoanCalcController.java
> +public class LoanCalcController {
Подскажи, вам на лекции сказали всю логику через static методы сделать?

2021-08-16 15:47 UTC, kkmikhaylova requested changes

2021-08-16 15:47 UTC, kkmikhaylova commented on app/src/main/java/com/tinkoff/edu/app/LoanCalcRepository.java
> +        ++requestId;
Можно написать сразу 
`return ++requestId;`
Прелесть префиксных и постфиксных операций в том, что для них не нужно выделять переменную и отдельную строку. Получаем экономию ресурсов и улучшенную читаемость

2021-08-16 15:54 UTC, PkozlovTCS commented on app/src/main/java/com/tinkoff/edu/app/LoanCalcRepository.java
> +        ++requestId;
исправил

2021-08-16 15:59 UTC, kkmikhaylova approved these changes
Хорошая работа :)

2021-08-16 16:27 UTC, merged